CREATE TABLE FACULTIES (
    faculty_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    faculty VARCHAR2(10) NOT NULL UNIQUE,
    faculty_name VARCHAR2(120) NOT NULL UNIQUE,
    dean VARCHAR2(150) NOT NULL UNIQUE
);

CREATE TABLE PULPITS (
    pulpit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    faculty_id NUMBER,
    pulpit VARCHAR2(120) NOT NULL UNIQUE,
    head_of_pulpit VARCHAR2(150) NOT NULL UNIQUE,
    CONSTRAINT fk_pulpits_faculty FOREIGN KEY (faculty_id) REFERENCES FACULTIES(faculty_id)
);

CREATE TABLE SPECIALTIES (
    specialty_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    specialty VARCHAR2(150),
    years_of_study NUMBER NOT NULL,
    degree VARCHAR2(50) NOT NULL,
    pulpit_id NUMBER,
    CONSTRAINT fk_specialties_pulpit FOREIGN KEY (pulpit_id) REFERENCES PULPITS(pulpit_id)
);

CREATE TABLE SUBJECTS (
    subject_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subject VARCHAR2(150) NOT NULL,
    pulpit_id NUMBER,
    CONSTRAINT fk_subjects_pulpit FOREIGN KEY (pulpit_id) REFERENCES PULPITS(pulpit_id)
);

CREATE TABLE TEACHERS (
    teacher_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    teacher VARCHAR2(150) NOT NULL,
    position VARCHAR2(75) NOT NULL,
    pulpit_id NUMBER,
    CONSTRAINT fk_teachers_pulpit FOREIGN KEY (pulpit_id) REFERENCES PULPITS(pulpit_id)
);

CREATE TABLE SUBJECT_TEACHER (
    teacher_id NUMBER NOT NULL,
    subject_id NUMBER NOT NULL,
    CONSTRAINT pk_subject_teacher PRIMARY KEY (teacher_id, subject_id),
    CONSTRAINT fk_st_teacher FOREIGN KEY (teacher_id) REFERENCES TEACHERS(teacher_id),
    CONSTRAINT fk_st_subject FOREIGN KEY (subject_id) REFERENCES SUBJECTS(subject_id)
);

CREATE TABLE STUDENTS (
    student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student VARCHAR2(150) NOT NULL,
    specialty_id NUMBER,
    course NUMBER NOT NULL,
    grup NUMBER NOT NULL,
    subgroup NUMBER NOT NULL,
    CONSTRAINT fk_students_specialty FOREIGN KEY (specialty_id) REFERENCES SPECIALTIES(specialty_id)
);

CREATE TABLE EXAMS (
    exam_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    exam_date DATE NOT NULL,
    exam_auditorium VARCHAR2(15) NOT NULL,
    teacher_id NUMBER,
    subject_id NUMBER,
    CONSTRAINT fk_exams_teacher FOREIGN KEY (teacher_id) REFERENCES TEACHERS(teacher_id),
    CONSTRAINT fk_exams_subject FOREIGN KEY (subject_id) REFERENCES SUBJECTS(subject_id)
);

CREATE TABLE GRADES (
    grade_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    subject_id NUMBER,
    grade NUMBER,
    CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES STUDENTS(student_id),
    CONSTRAINT fk_grades_subject FOREIGN KEY (subject_id) REFERENCES SUBJECTS(subject_id)
);