-- DROP TABLE GRADES CASCADE CONSTRAINTS;
-- DROP TABLE EXAMS CASCADE CONSTRAINTS;
-- DROP TABLE SUBJECT_TEACHER CASCADE CONSTRAINTS;
-- DROP TABLE STUDENTS CASCADE CONSTRAINTS;
-- DROP TABLE TEACHERS CASCADE CONSTRAINTS;
-- DROP TABLE SUBJECTS CASCADE CONSTRAINTS;
-- DROP TABLE SPECIALTIES CASCADE CONSTRAINTS;
-- DROP TABLE PULPITS CASCADE CONSTRAINTS;
-- DROP TABLE FACULTIES CASCADE CONSTRAINTS;



INSERT INTO FACULTIES(faculty, faculty_name, dean) VALUES('ТОВ','Технологический','Смирнов А.А.');
INSERT INTO FACULTIES(faculty, faculty_name, dean) VALUES('ИТ','Информационные технологии','Блинова Е.В.');
INSERT INTO FACULTIES(faculty, faculty_name, dean) VALUES('ХТ','Химический','Кузнецов Д.Д.');
INSERT INTO FACULTIES(faculty, faculty_name, dean) VALUES('ЛХ','Логистика','Попов В.В.');
INSERT INTO FACULTIES(faculty, faculty_name, dean) VALUES('ФЭ','Факультет экономики','Михайлова М.М.');


INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(1,'ТОВ-1','Смирнов А.А.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(1,'ТОВ-2','Васильев В.В.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(1,'ТОВ-Мат','Павлов П.П.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(2,'ПИ','Смелов В.В.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(2,'ИСиТ','Блинова Е.В.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(2,'ПОиСУ','Кузнецова К.К.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(2,'ИСиТ-МП','Иванова И.И.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(3,'ХТИТ-ХТ','Кузнецов Д.Д.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(3,'ХТИТ-Хим','Федорова Ф.Ф.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(3,'ХТИТ-Физ','Сергеев С.С.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(4,'ЛХФ-Лог','Попов В.В.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(4,'ЛХФ-Эк','Савельева С.С.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(4,'ЛХФ-Мен','Тимофеев Т.Т.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(5,'ФЭ-Эк','Николаев Н.Н.');
INSERT INTO PULPITS(faculty_id, pulpit, head_of_pulpit) VALUES(5,'ФЭ-Фин','Дмитриева Д.Д.');


INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Программная инженерия',4,'Бакалавр',4);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Мобильная разработка',4,'Бакалавр',4);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Цифровой дизайн',4,'Бакалавр',5);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Веб-разработка',4,'Бакалавр',6);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Кибербезопасность',4,'Бакалавр',4);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Химическая технология',5,'Специалист',8);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Биотехнология',5,'Специалист',9);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Логистика',4,'Бакалавр',11);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Экономика',4,'Бакалавр',14);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Финансы',4,'Бакалавр',15);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Технологии общего назначения',4,'Бакалавр',1);
INSERT INTO SPECIALTIES(specialty, years_of_study, degree, pulpit_id) VALUES('Управление персоналом',4,'Бакалавр',12);


INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Базы данных',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Операционные системы',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('ПСКП',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('ОАиП',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('ТРВП',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Алгоритмы и структуры данных',6);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Математический анализ',7);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Дискретная математика',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Физика',10);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Химия',9);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Компьютерная графика',7);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Веб-программирование',6);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Мобильная разработка',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Криптография',4);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Сети и телекоммуникации',7);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Экономика предприятия',14);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Статистика',14);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Бухгалтерский учет',15);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Менеджмент',12);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Логистика',11);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Технологические процессы',1);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Материаловедение',2);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Термодинамика',15);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Экология',9);
INSERT INTO SUBJECTS(subject, pulpit_id) VALUES('Иностранный язык',7);


INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Смелов В.В.','Зав. кафедрой ПИ',4);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Блинова Е.В.','Зав. кафедрой ИСиТ',5);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Нистюк О.А.','Ст. преподаватель',5);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Некрасова А.Н.','Ассистент',4);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Путинцев П.П.','Доцент',4);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Крылова К.К.','Доцент',5);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Иванов И.И.','Профессор',7);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Петров П.П.','Доцент',6);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Сидоров С.С.','Ст. преподаватель',8);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Козлов К.К.','Доцент',11);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Михайлов М.М.','Профессор',14);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Федоров Ф.Ф.','Зав. кафедрой',9);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Васильев В.В.','Доцент',2);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Николаева Н.Н.','Ст. преподаватель',15);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Дмитриев Д.Д.','Доцент',15);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Кузнецов К.К.','Ассистент',6);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Павлова П.П.','Ст. преподаватель',3);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Сергеев С.С.','Доцент',10);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Тимофеев Т.Т.','Профессор',13);
INSERT INTO TEACHERS(teacher, position, pulpit_id) VALUES('Савельев С.С.','Доцент',12);


INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(1,1);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(1,3);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(2,1);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(2,2);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(3,1);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(4,5);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(5,7);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(5,8);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(6,9);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(6,16);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(7,25);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(7,12);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(8,13);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(8,14);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(9,10);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(9,24);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(10,20);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(10,19);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(11,17);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(11,18);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(12,23);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(12,9);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(13,22);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(13,21);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(14,19);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(14,15);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(15,18);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(15,17);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(16,6);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(16,8);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(17,7);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(17,25);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(18,15);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(18,4);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(19,19);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(19,20);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(20,16);
INSERT INTO SUBJECT_TEACHER(subject_id, teacher_id) VALUES(20,17);

INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Дмитроченко Кирилл',1,3,8,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Иванов Алексей',1,3,6,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Петрова Мария',1,3,7,2);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Сидоров Дмитрий',1,3,9,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Козлова Анна',1,3,10,2);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Смирнов Иван',1,3,4,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Васильева Ольга',1,3,2,2);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Кузнецов Максим',1,3,5,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Федорова Елена',1,3,6,2);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Попов Сергей',1,3,4,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Николаев Дима',2,2,7,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Михайлова Катя',2,2,7,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Тимофеев Артем',2,2,2,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Савельева Алина',2,2,2,2);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Павлов Никита',4,4,10,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Сергеева Вика',4,4,9,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Лебедев Саша',4,4,2,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Григорьев Влад',5,1,5,1);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Зайцева Маша',5,1,7,2);
INSERT INTO STUDENTS(student, specialty_id, course, grup, subgroup) VALUES('Захаров Илья',5,1,9,1);



INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-01-15 10:00','YYYY-MM-DD HH24:MI'),'204-1',2,1);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-01-20 10:00','YYYY-MM-DD HH24:MI'),'309-1',1,3);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-01-25 10:00','YYYY-MM-DD HH24:MI'),'308-4',3,1);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-01-28 10:00','YYYY-MM-DD HH24:MI'),'113-4',1,4);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-01-30 14:00','YYYY-MM-DD HH24:MI'),'204-4',4,2);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-02-02 09:00','YYYY-MM-DD HH24:MI'),'309-4',5,7);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-02-05 12:00','YYYY-MM-DD HH24:MI'),'308-1',6,9);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-02-08 15:00','YYYY-MM-DD HH24:MI'),'113-4',7,25);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-02-10 10:00','YYYY-MM-DD HH24:MI'),'204-1',8,13);
INSERT INTO EXAMS(exam_date, exam_auditorium, teacher_id, subject_id) VALUES(TO_DATE('2026-02-12 13:00','YYYY-MM-DD HH24:MI'),'309-4',3,11);


INSERT INTO GRADES(student_id, subject_id, grade) VALUES(1,1,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(1,2,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(1,3,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(2,1,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(2,2,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(2,3,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(3,1,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(3,2,4);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(3,3,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(4,1,1);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(4,2,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(4,3,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(5,1,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(5,2,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(5,3,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(1,4,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(2,4,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(3,4,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(4,4,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(5,4,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(1,5,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(2,5,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(3,5,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(4,5,1);

INSERT INTO GRADES(student_id, subject_id, grade) VALUES(6,1,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(6,2,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(6,3,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(7,1,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(7,2,1);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(7,3,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(8,1,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(8,2,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(8,3,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(9,1,4);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(9,2,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(9,3,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(10,1,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(10,2,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(10,3,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(6,4,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(7,4,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(8,4,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(9,4,1);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(10,4,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(6,5,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(7,5,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(8,5,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(9,5,9);

INSERT INTO GRADES(student_id, subject_id, grade) VALUES(11,1,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(11,2,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(11,3,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(12,1,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(12,2,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(12,3,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(13,1,4);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(13,2,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(13,3,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(14,1,1);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(14,2,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(14,3,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(15,1,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(15,2,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(15,3,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(11,4,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(12,4,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(13,4,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(14,4,4);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(15,4,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(11,5,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(12,5,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(13,5,1);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(14,5,7);

INSERT INTO GRADES(student_id, subject_id, grade) VALUES(16,1,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(16,2,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(16,3,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(17,1,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(17,2,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(17,3,4);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(18,1,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(18,2,1);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(18,3,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(19,1,5);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(19,2,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(19,3,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(20,1,2);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(20,2,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(20,3,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(16,4,7);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(17,4,1);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(18,4,10);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(19,4,4);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(20,4,8);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(16,5,6);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(17,5,3);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(18,5,9);
INSERT INTO GRADES(student_id, subject_id, grade) VALUES(19,5,2);


commit;